# -*- coding: utf-8 -*-
# AMBRACE step7: models domain subpackage (Grouping Strategy A)

# Alembic / metadata registration: import EVERY model so Base.metadata is complete.
from app.models.base import Base
from app.models.user import User, UserState, UserDndSettings, PrivacyRequest, BrowserSnapshot, AccountInvite, GlobalUserFact, AccountPurgeJob
from app.models.character import AICharacter, CharacterState, CharacterStateHistory, RelationshipEvent, StateTriggerLog, StorylineEvent, ProactiveStorylineItem, ProactiveSettings, HolidayPreference, ProactiveMessageLog, ProactiveTriggerLog
from app.models.chat import ChatSession, ChatMessage, ChatGroup, ChatGroupMember, ChatGroupMessage, GroupMemory, GroupCharCognition, AIChat
from app.models.memory import Memory, DailySummary, ConversationTopic, StageMemory, ReflectionLog, ProcessedExtraction, SharedEvent, WeaveCard, WeaveCardMemory, WeaveCardCharacter, LorebookEntry, WorldFact, MemoryArchive, MemoryWriteReceipt, ProspectiveIntent
from app.models.life import LifeState, LifeActivityLog, LifeArtifact, LifeInterest, LifeGoal, LifeSchedule, LifeFollowup, LifeChatIntent, AIDiary, UserDiary, UserMemo, AIMoment, MomentLike, MomentAILike, MomentComment, MomentReadMark, ScheduledEvent, TimelineEvent, ImageGenTask, ImageGenConfig, UserRhythm, UserWorkflow, UserEmojiPack, UserCustomEmoji
from app.models.pet import Pet, PetActivity
from app.models.agent import AgentTask, AgentTaskLog, LlmUsage, LlmUsageLimit, UserLlmLimit, TaskLlmConfig, EmotionCareTask, ToolPermission, PendingPermissionAction
from app.models.mcp import MCPServer, McpCallLog
from app.models.plugin import Plugin, PluginStore, PluginConsent
from app.models.config import ApiConfig, VlmConfig, SpeechConfig, MultimodalConfig, MarketplaceConfig, RuntimeFlag, UserRuntimeFlag, UserLlmConfig, FlagSetting, ServerSetting
from app.models.admin import AdminAuditLog  # 控制台审计域（账号独立 P2，2026-09-19）
from app.models.social import PlatformProfile, SocialMemory  # X5：渠道自有模型迁至渠道扩展包，加载期注册进 metadata
from app.models.device import PhoneDesktop, PhoneLayout, CalendarNote, BrowserHistory, MemoNote, PhoneSnapshot, CheckInRequest, PhoneAutoState, UserDeviceToken, DeviceActionTarget, DeviceActionPlugin, DeviceActionPolicy  # X7-M4c-3 行动名单两表 + C1b 行动策略
from app.models.game import (
    GameSession, GamePlayer, GameEvent, GameMemory,
    GameContentOverride, GameStats, GameAchievement,
)
from app.models.channel import ChannelBinding  # 一机多主：渠道绑定内核一等公民（2026-09-05）
from app.models.domain_event import DomainEvent  # 3.10 事件流水（append-only，2026-09-08）

__all__ = [
    "Base",
    "AICharacter",
    "AIChat",
    "AIDiary",
    "AIMoment",
    "AccountInvite",
    "AccountPurgeJob",
    "GlobalUserFact",
    "AgentTask",
    "AgentTaskLog",
    "ApiConfig",
    "AdminAuditLog",
    "FlagSetting",
    "ServerSetting",
    "BrowserHistory",
    "BrowserSnapshot",
    "CalendarNote",
    "ChannelBinding",
    "CharacterState",
    "CharacterStateHistory",
    "ChatGroup",
    "ChatGroupMember",
    "ChatGroupMessage",
    "GroupMemory",
    "GroupCharCognition",
    "ChatMessage",
    "ChatSession",
    "CheckInRequest",
    "ConversationTopic",
    "DailySummary",
    "DomainEvent",
    "EmotionCareTask",
    "HolidayPreference",
    "ImageGenConfig",
    "ImageGenTask",
    "LifeActivityLog",
    "LifeArtifact",
    "LifeGoal",
    "LifeInterest",
    "LifeSchedule",
    "LifeFollowup",
    "LifeChatIntent",
    "LifeState",
    "LlmUsage",
    "LlmUsageLimit",
    "UserLlmLimit",
    "LorebookEntry",
    "MCPServer",
    "MarketplaceConfig",
    "McpCallLog",
    "MemoNote",
    "Memory",
    "MomentAILike",
    "MomentComment",
    "MomentLike",
    "MomentReadMark",
    "MultimodalConfig",
    "PendingPermissionAction",
    "Pet",
    "PetActivity",
    "PhoneAutoState",
    "UserDeviceToken",
    "PhoneDesktop",
    "PhoneLayout",
    "PhoneSnapshot",
    "PlatformProfile",
    "Plugin",
    "PluginStore",
    "PluginConsent",
    "PrivacyRequest",
    "ProactiveMessageLog",
    "ProactiveSettings",
    "ProactiveStorylineItem",
    "ProactiveTriggerLog",
    "ProcessedExtraction",
    "ReflectionLog",
    "RelationshipEvent",
    "RuntimeFlag",
    "UserRuntimeFlag",
    "ScheduledEvent",
    "SharedEvent",
    "SocialMemory",
    "SpeechConfig",
    "StageMemory",
    "StateTriggerLog",
    "StorylineEvent",
    "TaskLlmConfig",
    "TimelineEvent",
    "ToolPermission",
    "User",
    "UserCustomEmoji",
    "UserDiary",
    "UserDndSettings",
    "UserEmojiPack",
    "UserMemo",
    "UserRhythm",
    "UserState",
    "UserWorkflow",
    "VlmConfig",
    "UserLlmConfig",
    "WeaveCard",
    "WeaveCardCharacter",
    "WeaveCardMemory",
    "WorldFact",
    "MemoryArchive",
    "MemoryWriteReceipt",
    "ProspectiveIntent",
    "GameSession",
    "GamePlayer",
    "GameEvent",
    "GameMemory",
    "GameContentOverride",
    "GameStats",
    "GameAchievement",
    "DeviceActionTarget",
    "DeviceActionPlugin",
    "DeviceActionPolicy",
]
