# -*- coding: utf-8 -*-
# AMBRACE step7: models domain subpackage (Grouping Strategy A)

# Alembic / metadata registration: import EVERY model so Base.metadata is complete.
from app.models.base import Base
from app.models.user import User, UserState, UserDndSettings, PrivacyRequest, BrowserSnapshot, AccountInvite, GlobalUserFact
from app.models.character import AICharacter, CharacterState, CharacterStateHistory, RelationshipEvent, StateTriggerLog, StorylineEvent, ProactiveStorylineItem, ProactiveSettings, HolidayPreference, ProactiveMessageLog, ProactiveTriggerLog
from app.models.chat import ChatSession, ChatMessage, ChatGroup, ChatGroupMember, ChatGroupMessage, GroupMemory, AIChat
from app.models.memory import Memory, DailySummary, ConversationTopic, StageMemory, ReflectionLog, ProcessedExtraction, SharedEvent, WeaveCard, WeaveCardMemory, WeaveCardCharacter, LorebookEntry, WorldFact, MemoryArchive, ProspectiveIntent
from app.models.life import LifeState, LifeActivityLog, LifeArtifact, LifeInterest, LifeGoal, LifeSchedule, LifeFollowup, LifeChatIntent, AIDiary, UserDiary, UserMemo, AIMoment, MomentLike, MomentAILike, MomentComment, MomentReadMark, ScheduledEvent, TimelineEvent, ImageGenTask, ImageGenConfig, UserRhythm, UserWorkflow, UserEmojiPack, UserCustomEmoji
from app.models.pet import Pet, PetActivity
from app.models.agent import AgentTask, AgentTaskLog, LlmUsage, LlmUsageLimit, TaskLlmConfig, EmotionCareTask, ToolPermission, PendingPermissionAction
from app.models.mcp import MCPServer, McpCallLog
from app.models.plugin import Plugin, PluginStore
from app.models.config import ApiConfig, VlmConfig, SpeechConfig, MultimodalConfig, MarketplaceConfig, RuntimeFlag, UserLlmConfig
from app.models.social import PlatformProfile, SocialMemory  # X5：渠道自有模型迁至渠道扩展包，加载期注册进 metadata
from app.models.device import PhoneDesktop, PhoneLayout, CalendarNote, BrowserHistory, MemoNote, PhoneSnapshot, CheckInRequest, PhoneAutoState, UserDeviceToken
from app.models.game import GameSession, GamePlayer, GameEvent, GameMemory

__all__ = [
    "Base",
    "AICharacter",
    "AIChat",
    "AIDiary",
    "AIMoment",
    "AccountInvite",
    "GlobalUserFact",
    "AgentTask",
    "AgentTaskLog",
    "ApiConfig",
    "BrowserHistory",
    "BrowserSnapshot",
    "CalendarNote",
    "CharacterState",
    "CharacterStateHistory",
    "ChatGroup",
    "ChatGroupMember",
    "ChatGroupMessage",
    "GroupMemory",
    "ChatMessage",
    "ChatSession",
    "CheckInRequest",
    "ConversationTopic",
    "DailySummary",
    "EmotionCareTask",
    "HolidayPreference",
    "ImageGenConfig",
    "ImageGenTask",
    "LifeActivityLog",
    "LifeArtifact",
    "LifeGoal",
    "LifeInterest",
    "LifeSchedule",
    "LifeFollowup",
    "LifeChatIntent",
    "LifeState",
    "LlmUsage",
    "LlmUsageLimit",
    "LorebookEntry",
    "MCPServer",
    "MarketplaceConfig",
    "McpCallLog",
    "MemoNote",
    "Memory",
    "MomentAILike",
    "MomentComment",
    "MomentLike",
    "MomentReadMark",
    "MultimodalConfig",
    "PendingPermissionAction",
    "Pet",
    "PetActivity",
    "PhoneAutoState",
    "UserDeviceToken",
    "PhoneDesktop",
    "PhoneLayout",
    "PhoneSnapshot",
    "PlatformProfile",
    "Plugin",
    "PluginStore",
    "PrivacyRequest",
    "ProactiveMessageLog",
    "ProactiveSettings",
    "ProactiveStorylineItem",
    "ProactiveTriggerLog",
    "ProcessedExtraction",
    "ReflectionLog",
    "RelationshipEvent",
    "RuntimeFlag",
    "ScheduledEvent",
    "SharedEvent",
    "SocialMemory",
    "SpeechConfig",
    "StageMemory",
    "StateTriggerLog",
    "StorylineEvent",
    "TaskLlmConfig",
    "TimelineEvent",
    "ToolPermission",
    "User",
    "UserCustomEmoji",
    "UserDiary",
    "UserDndSettings",
    "UserEmojiPack",
    "UserMemo",
    "UserRhythm",
    "UserState",
    "UserWorkflow",
    "VlmConfig",
    "UserLlmConfig",
    "WeaveCard",
    "WeaveCardCharacter",
    "WeaveCardMemory",
    "WorldFact",
    "MemoryArchive",
    "ProspectiveIntent",
    "GameSession",
    "GamePlayer",
    "GameEvent",
    "GameMemory",
]
